# ISP Gateway Ping Monitor Configuration - Multi-ISP Support
# Each location can have multiple ISP connections for redundancy monitoring

locations:
  # Location 1 - Main Office (Dual ISP setup)
  iyc:
    description: "Main office with primary and backup ISP"
    isps:
      primary:
        gateway_ip: "117.239.66.131"
        zabbix_hostname: "iyc-primary-bsnl"
        
#      backup:
#        gateway_ip: "47.247.113.49"
#        zabbix_hostname: "iyc-backup-jio"
      
# Configuration notes:
# - Each location can have multiple ISPs under the 'isps' section
# - ISP identifiers (primary, backup, cellular, etc.) are flexible - use descriptive names
# - gateway_ip: The IP address of the ISP's gateway/router
# - zabbix_hostname: Must match the hostname configured in Zabbix server (unique per ISP)
# - isp_name: Human readable ISP provider name
# - connection_type: Description of the connection role (Primary, Backup, etc.)

# To find gateway IPs:
# - Windows: ipconfig /all (look for Default Gateway)
# - Linux/Mac: ip route show | grep default
# - Router admin: usually shows WAN gateway for each connection
